import { NO_VKC, type VKC } from './constants';
import { VK_SHARED } from './shared';

export const VK_ANSI: Record<string, VKC> = {
    ...VK_SHARED,
    KeyA: { mac: 0x00, windows: 0x41, keyType: "VKC", legend: "A" },
    KeyS: { mac: 0x01, windows: 0x53, keyType: "VKC", legend: "S" },
    KeyD: { mac: 0x02, windows: 0x44, keyType: "VKC", legend: "D" },
    KeyF: { mac: 0x03, windows: 0x46, keyType: "VKC", legend: "F" },
    KeyH: { mac: 0x04, windows: 0x48, keyType: "VKC", legend: "H" },
    KeyG: { mac: 0x05, windows: 0x47, keyType: "VKC", legend: "G" },
    KeyZ: { mac: 0x06, windows: 0x5A, keyType: "VKC", legend: "Z" },
    KeyX: { mac: 0x07, windows: 0x58, keyType: "VKC", legend: "X" },
    KeyC: { mac: 0x08, windows: 0x43, keyType: "VKC", legend: "C" },
    KeyV: { mac: 0x09, windows: 0x56, keyType: "VKC", legend: "V" },
    KeyB: { mac: 0x0B, windows: 0x42, keyType: "VKC", legend: "B" },
    KeyQ: { mac: 0x0C, windows: 0x51, keyType: "VKC", legend: "Q" },
    KeyW: { mac: 0x0D, windows: 0x57, keyType: "VKC", legend: "W" },
    KeyE: { mac: 0x0E, windows: 0x45, keyType: "VKC", legend: "E" },
    KeyR: { mac: 0x0F, windows: 0x52, keyType: "VKC", legend: "R" },
    KeyY: { mac: 0x10, windows: 0x59, keyType: "VKC", legend: "Y" },
    KeyT: { mac: 0x11, windows: 0x54, keyType: "VKC", legend: "T" },
    Digit1: { mac: 0x12, windows: 0x31, keyType: "VKC", legend: "1" },
    Digit2: { mac: 0x13, windows: 0x32, keyType: "VKC", legend: "2" },
    Digit3: { mac: 0x14, windows: 0x33, keyType: "VKC", legend: "3" },
    Digit4: { mac: 0x15, windows: 0x34, keyType: "VKC", legend: "4" },
    Digit6: { mac: 0x16, windows: 0x36, keyType: "VKC", legend: "6" },
    Digit5: { mac: 0x17, windows: 0x35, keyType: "VKC", legend: "5" },
    Equal: { mac: 0x18, windows: 0xBB, keyType: "VKC", legend: "=" },
    Digit9: { mac: 0x19, windows: 0x39, keyType: "VKC", legend: "9" },
    Digit7: { mac: 0x1A, windows: 0x37, keyType: "VKC", legend: "7" },
    Minus: { 
        mac: 0x1B, 
        windows: 0xBD, 
        keyType: "VKC", 
        legend: "-", 
        description: "dash;minus;hyphen" 
    },
    Digit8: { mac: 0x1C, windows: 0x38, keyType: "VKC", legend: "8" },
    Digit0: { mac: 0x1D, windows: 0x30, keyType: "VKC", legend: "0" },
    BracketRight: { mac: 0x1E, windows: 0xDD, keyType: "VKC", legend: "]" },
    KeyO: { mac: 0x1F, windows: 0x4F, keyType: "VKC", legend: "O" },
    KeyU: { mac: 0x20, windows: 0x55, keyType: "VKC", legend: "U" },
    BracketLeft: { mac: 0x21, windows: 0xDB, keyType: "VKC", legend: "[" },
    KeyI: { mac: 0x22, windows: 0x49, keyType: "VKC", legend: "I" },
    KeyP: { mac: 0x23, windows: 0x50, keyType: "VKC", legend: "P" },
    KeyL: { mac: 0x25, windows: 0x4C, keyType: "VKC", legend: "L" },
    KeyJ: { mac: 0x26, windows: 0x4A, keyType: "VKC", legend: "J" },
    Quote: { mac: 0x27, windows: 0xDE, keyType: "VKC", legend: "'" },
    KeyK: { mac: 0x28, windows: 0x4B, keyType: "VKC", legend: "K" },
    Semicolon: { mac: 0x29, windows: 0xBA, keyType: "VKC", legend: ";" },
    Backslash: { 
        mac: 0x2A, 
        windows: 0xDC, 
        keyType: "VKC", 
        legend: "\\",
        description: "backslash;reverse solidus" 
    },
    Comma: { mac: 0x2B, windows: 0xBC, keyType: "VKC", legend: "," },
    Slash: { 
        mac: 0x2C, 
        windows: 0xBF, 
        keyType: "VKC", 
        legend: "/",
        description: "slash;solidus" 
    },
    KeyN: { mac: 0x2D, windows: 0x4E, keyType: "VKC", legend: "N" },
    KeyM: { mac: 0x2E, windows: 0x4D, keyType: "VKC", legend: "M" },
    Period: { mac: 0x2F, windows: 0xBE, keyType: "VKC", legend: "." },
    Backquote: { mac: 0x32, windows: 0xC0, keyType: "VKC", legend: "`" },
    
    // Numpad
    NumpadDecimal: { mac: 0x41, windows: 0x6E, keyType: "VKC", legend: ".", description: "period" },
    NumpadMultiply: { mac: 0x43, windows: 0x6A, keyType: "VKC", legend: "*", description: "multiply" },
    NumpadAdd: { mac: 0x45, windows: 0x6B, keyType: "VKC", legend: "+", description: "add" },
    NumLock: { mac: 0x47, windows: 0x90, keyType: "VKC", legend: "⇭", description: "num lock" },
    NumpadDivide: { mac: 0x4B, windows: 0x6F, keyType: "VKC", legend: "/", description: "slash;solidus" },
    NumpadEnter: { mac: 0x4C, windows: 0x0D, keyType: "VKC", legend: "⏎", description: "enter" },
    NumpadSubtract: { mac: 0x4E, windows: 0x6D, keyType: "VKC", legend: "-", description: "dash;minus;hyphen" },
    NumpadEqual: { mac: 0x51, windows: NO_VKC, keyType: "VKC", legend: "=", description: "equal" },
    Numpad0: { mac: 0x52, windows: 0x60, keyType: "VKC", legend: "0", description: "zero" },
    Numpad1: { mac: 0x53, windows: 0x61, keyType: "VKC", legend: "1", description: "one" },
    Numpad2: { mac: 0x54, windows: 0x62, keyType: "VKC", legend: "2", description: "two" },
    Numpad3: { mac: 0x55, windows: 0x63, keyType: "VKC", legend: "3", description: "three" },
    Numpad4: { mac: 0x56, windows: 0x64, keyType: "VKC", legend: "4", description: "four" },
    Numpad5: { mac: 0x57, windows: 0x65, keyType: "VKC", legend: "5", description: "five" },
    Numpad6: { mac: 0x58, windows: 0x66, keyType: "VKC", legend: "6", description: "six" },
    Numpad7: { mac: 0x59, windows: 0x67, keyType: "VKC", legend: "7", description: "seven" },
    Numpad8: { mac: 0x5B, windows: 0x68, keyType: "VKC", legend: "8", description: "eight" },
    Numpad9: { mac: 0x5C, windows: 0x69, keyType: "VKC", legend: "9", description: "nine" },
    NumpadComma: { mac: 0x5F, windows: NO_VKC, keyType: "VKC", legend: ",", description: "comma" },
};
